### ISSUE TITLE
I did not receive any data

### ISSUE THREAD

**Issue by ucakmakci** [v-zhuravlev/zabbix-syslog#1]
Hi,

My zabbix version 2.4.8

I made all the settings. I did not receive any data.

My steps,

###########################################################
yum install perl-JSON-XS perl-libwww-perl perl-LWP-Protocol-https perl-Config-General
###########################################################
cpanm install CHI
cp zabbix_syslog_create_urls.pl /etc/zabbix/scripts/zabbix_syslog_create_urls.pl
chmod +x /etc/zabbix/scripts/zabbix_syslog_create_urls.pl
cp zabbix_syslog_lkp_host.pl /etc/zabbix/scripts/zabbix_syslog_lkp_host.pl
chmod +x /etc/zabbix/scripts/zabbix_syslog_lkp_host.pl
mkdir /etc/zabbix/scripts/lib
cp lib/ZabbixAPI.pm /etc/zabbix/scripts/lib
cp zabbix_syslog.cfg /etc/zabbix/zabbix_syslog.cfg
sudo chown zabbix:zabbix /etc/zabbix/zabbix_syslog.cfg
sudo chmod 700 /etc/zabbix/zabbix_syslog.cfg
###########################################################
vi /etc/zabbix/zabbix_syslog.cfg
admin password set.
###########################################################
/etc/rsyslog.d/zabbix_rsyslog.conf 
$template RFC3164fmt,"<%PRI%>%TIMESTAMP% %HOSTNAME% %syslogtag%%msg%"
$template network-fmt,"%TIMESTAMP:::date-rfc3339% [%fromhost-ip%] %pri-text% %syslogtag%%msg%\n"
#exclude unwanted messages:
:msg, contains, "Child connection from" ~
:msg, contains, "exit after auth (ubnt): Disconnect received" ~
:msg, contains, "password auth succeeded for 'ubnt' from ::ffff:xx.xx.xx.xx" ~
:msg, contains, "password auth succeeded for 'ubnt' from" ~
:msg, contains, "exit before auth: Exited normally" ~
if $fromhost-ip != '127.0.0.1' then ^/etc/zabbix/scripts/zabbix_syslog_lkp_host.pl;network-fmt       
if $fromhost-ip != '127.0.0.1' then /var/log/network.log;network-fmt
& ~
###########################################################
vim /etc/rsyslog.conf
modify 
$ModLoad imudp
$UDPServerRun 514
service rsyslog restart
###########################################################
Rsyslog is working. Data is coming
2016-12-22T16:22:34+03:00 [101.10.100.3] kern.err v-zhuravlev/zabbix-syslog
2016-12-22T16:22:34+03:00 [101.10.100.3] kern.err v-zhuravlev/zabbix-syslog
2016-12-22T16:22:35+03:00 [101.10.100.3] kern.err v-zhuravlev/zabbix-syslog
2016-12-22T16:22:35+03:00 [101.10.100.3] kern.err v-zhuravlev/zabbix-syslog
2016-12-22T16:22:36+03:00 [101.10.100.3] kern.err v-zhuravlev/zabbix-syslog
2016-12-22T16:22:36+03:00 [101.10.100.3] kern.err v-zhuravlev/zabbix-syslog
2016-12-22T16:22:37+03:00 [101.10.100.3] kern.err v-zhuravlev/zabbix-syslog
###########################################################
I have installed the syslog-template.. assign computer and add snmp interface 161

Script not working

How can i find my mistake

please help me

**Comment by v-zhuravlev** [comment]
try to run it yourself: 
`/etc/zabbix/scripts/zabbix_syslog_lkp_host.pl '[101.10.100.3] kern.err v-zhuravlev/zabbix-syslog'`
- do you have any errors?
- have you got the host in zabbix with 101.10.100.3 ip as host interface with `item` key named `syslog`?

**Comment by ucakmakci** [comment]
Hello!

Script worked manualy..

Local time is blank.
find attached file

![zbx](https://cloud.githubusercontent.com/assets/11998407/21448021/7d60e98e-c8ee-11e6-8932-1555ca3d6e77.png)

**Comment by v-zhuravlev** [comment]
oh , sorry with time that will be:
`/etc/zabbix/scripts/zabbix_syslog_lkp_host.pl '2016-12-22T16:22:37+03:00 [101.10.100.3] kern.err v-zhuravlev/zabbix-syslog'`

There might be some difference between running this under your user and rsyslog's user (root?)
try to run it under root or what rsyslog user you have.

**Comment by ucakmakci** [comment]
hi,

rsyslogs procces run root user

![zbx1](https://cloud.githubusercontent.com/assets/11998407/21453396/8af376bc-c91f-11e6-9999-c891cc8a8a84.png)

**Comment by v-zhuravlev** [comment]
Have you tried running script under root?

**Comment by ucakmakci** [comment]
This script is working with root user and zabbix user without problem manually. The problem is rsyslog user cant automate it.

**Comment by ucakmakci** [comment]
Hi,
The perl script below can be automated with rsyslog but the script you gave me have a problem with automating with rsyslog. Both scripts have exact same permissions. I guess the problem is about perl modules on the script you gave.
For exampIe i setup CHI module manually. Maybe this can cause the problem. 
Maybe another one. Any idea?
test.pl
################################################################
#!/usr/bin/perl
open LOG, ">>/deploy/log.txt";
print LOG "Here is a new log entry\n";
close LOG;
################################################################
OS is CentOS 7 
Perl vers. v5.16.3
Zabbix vers. 2.4.8

Thank you for help,

**Comment by v-zhuravlev** [comment]
try to redirect `>` STDERR and STDOUT output from script to some file in rsyslog config. You would probably see that CHI module cannot be located.

**Comment by ucakmakci** [comment]
I am sorry but i'm not really used to with perl scripting. So i cant really make it work with these redirections. Can you give me an example?

Thank you very much..

**Comment by ucakmakci** [comment]
I added this line
#############################################################################
if $fromhost-ip != '127.0.0.1' then ^/etc/zabbix/scripts/zabbix_syslog_lkp_host.pl >/tmp/myscript.log 2<&1;network-fmt
#############################################################################
I did not receive input, output and error output.

How should I write this line :(

**Comment by artem33region** [comment]
Hello, please help me.
When i am trying run script i have error.
[root@localhost /]# /etc/zabbix/scripts/zabbix_syslog_lkp_host.pl
Can't locate CHI.pm in @INC (@INC contains: /etc/zabbix/scripts/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /etc/zabbix/scripts/zabbix_syslog_lkp_host.pl line 11.
BEGIN failed--compilation aborted at /etc/zabbix/scripts/zabbix_syslog_lkp_host.pl line 11.

What is it mean?

**Comment by v-zhuravlev** [comment]
@artem33region , you don't have CHI perl module installed. Check README how to install it.

**Comment by artem33region** [comment]
How can i install this module? I already have executed command under root:
yum install perl-JSON-XS perl-libwww-perl perl-LWP-Protocol-https perl-Config-General

I have CentOS 7

I apologize for my English.

**Comment by v-zhuravlev** [comment]
use cpan to install it.

**Comment by v-zhuravlev** [comment]
Stop rsyslog daemon
run rsyslogd in the interactive mode: rsyslogd -n
open another terminal and send a test syslog message.
observe what actually script returns when processing this test syslog message.
For example:
[root@zabbix-lab vagrant]# rsyslogd -n
rsyslogd: error during config processing: STOP is followed by unreachable statements!  [v8.24.0 try http://www.rsyslog.com/e/2207 ]
Can't locate CHI.pm in @INC (@INC contains: /etc/zabbix/scripts/lib /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 .) at /etc/zabbix/scripts/zabbix_syslog_lkp_host.pl line 11.
BEGIN failed--compilation aborted at /etc/zabbix/scripts/zabbix_syslog_lkp_host.pl line 11.
rsyslogd: Child 15334 has terminated, reaped by main-loop. [v8.24.0 try http://www.rsyslog.com/e/0

**Comment by v-zhuravlev** [comment]
problem was that CHI module actually could no be found locatd for rsyslog in Centos 7 under root if installed with cpanm or CPAN. Please try new version of script without CHI: https://github.com/v-zhuravlev/zabbix-syslog/releases/tag/v3.0
