### ISSUE TITLE
Getting syslog information from a seperate syslog server

### ISSUE THREAD

**Issue by Altranoetic** [v-zhuravlev/zabbix-syslog#10]
Hello, apologies if this is a silly question. I guess it's somewhat of a feature request?

How would I go about getting the syslog information from a syslog server that's seperate from the Zabbix server, while still adding the devices & having them labeled by their own IPs (as opposed to adding an agent on the syslog server and monitoring that)?

I'm a little new to Zabbix in general, and while I've read a good chunk of the documentation some of it is still a tad confusing. I'm not opposed to modifying the scripts, although I don't know perl very well.

**Comment by v-zhuravlev** [comment]
Hi, If I got your question right, this repository is all about "about getting the syslog information from a syslog server that's seperate from the Zabbix server, while still adding the devices & having them labeled by their own IPs" 

You need to configure your syslog(must be rsyslog) to send messages to Zabbix server using script from this repo. Devices(hosts) will be identified in Zabbix by IP addresses. See README
