### ISSUE TITLE
Script broken in Zabbix 4.0

### ISSUE THREAD

**Issue by tecnologianano** [v-zhuravlev/zabbix-syslog#12]
In Zabbix 4.0, plain text protocol support is dropped and header is mandatory.

In consequence, this script generates tons of logs like this:

```
 25712:20181114:093830.826 Message from 127.0.0.1 is missing header. Message ignored.
 25708:20181114:093830.827 Message from 127.0.0.1 is missing header. Message ignored.
 25712:20181114:093831.427 Message from 127.0.0.1 is missing header. Message ignored.
```

I hope to find a way to solve this, but i'm not a developer. Any help is welcome.

More information here: https://support.zabbix.com/browse/ZBXNEXT-3581

**Comment by tecnologianano** [comment]
> In Zabbix 4.0, plain text protocol support is dropped and header is mandatory.
> 
> In consequence, this script generates tons of logs like this:
> 
> ```
>  25712:20181114:093830.826 Message from 127.0.0.1 is missing header. Message ignored.
>  25708:20181114:093830.827 Message from 127.0.0.1 is missing header. Message ignored.
>  25712:20181114:093831.427 Message from 127.0.0.1 is missing header. Message ignored.
> ```
> I hope to find a way to solve this, but i'm not a developer. Any help is welcome.
> 
> More information here: https://support.zabbix.com/browse/ZBXNEXT-3581

Solved doing some changes in zabbix_syslog_lkp_host.pl:

```
    # changed var name
    my $request_prev =
      sprintf
      "<req>\n<host>%s</host>\n<key>%s</key>\n<data>%s</data>\n</req>\n",
      encode_base64($hostname), encode_base64($item), encode_base64($data);

    # trying to fix header problem
    my $request = "ZBXD\1" . pack('<Q', length($request_prev)) . $request_prev;
```
More information about headers here: https://www.zabbix.com/documentation/4.0/manual/appendix/protocols/header_datalen

**Comment by v-zhuravlev** [comment]
sorry did you use latest version of the script ? I thought that this problem was solved in the latests commit.

**Comment by tecnologianano** [comment]
> sorry did you use latest version of the script ? I thought that this problem was solved in the latests commit.

I started using this script nearly 4 months ago, so yes, i think that i'm using the lastest version.

**Comment by v-zhuravlev** [comment]
The latest commit was 5 days ago, actually fixing that problem I think:
https://github.com/v-zhuravlev/zabbix-syslog/commit/39f17e9300d83838e8aeeee9a80a0462b741d90d

**Comment by tecnologianano** [comment]
> The latest commit was 5 days ago, actually fixing that problem I think:
> [39f17e9](https://github.com/v-zhuravlev/zabbix-syslog/commit/39f17e9300d83838e8aeeee9a80a0462b741d90d)

Sorry, that's right. I didn't check my script version. I'm closing this issue as solved. Thank you.
