### ISSUE TITLE
Login name or password is incorrect

### ISSUE THREAD

**Issue by msslava** [v-zhuravlev/zabbix-syslog#3]
Hello.
I would like to use your method on the zabbix.
I did everything as written in the wiki.
But the data does not come in zabbix.
When I do so:
`/etc/zabbix/scripts/zabbix_syslog_lkp_host.pl '[xxx.xx.xx.xxx] kern.err /var/log/syslog'`
I get
`Login name or password is incorrect`
I understand that the wrong credentials in the file
`/usr/local/etc/zabbix_syslog.cfg`
but they are correct. There is use the super administrator's credentials.
What can be wrong?

**Comment by v-zhuravlev** [comment]
Do you have any chars in the pass that require escaping ? not sure, but can you try to create another user with simple pass?

**Comment by msslava** [comment]
Yes, I tried to do so.
I used the user API and password api
The same mistake.
I enter all the credentials without quotes, as in your example.
Zabbix version 3.2

**Comment by v-zhuravlev** [comment]
do you have zabbix_syslog.cfg file in /etc/zabbix/?

**Comment by msslava** [comment]
No. 
I was guided by your article on habrahabr
There it was written 
`/usr/local/etc/zabbix_syslog.cfg`
Sorry, my fault.
It works without errors.
But the date in zabbix does not automatically arrive.
What can be wrong?

**Comment by v-zhuravlev** [comment]
date? what do you mean? It's in the message but not put into timestamp in zabbix ?

**Comment by msslava** [comment]
Sorry, I mean the log, it's empty.
In /var/log/syslog - OK
In zabbix frontend - empty

**Comment by v-zhuravlev** [comment]
common error is that some perl modules are not available under user `root`. check that
```
sudo su
/etc/zabbix/scripts/zabbix_syslog_lkp_host.pl '[xxx.xx.xx.xxx] kern.err /var/log/syslog'
```
sorry, i meant root.

**Comment by msslava** [comment]
Can I use a different system account?
I tried to do so:
`sudo chown user:user /etc/zabbix/zabbix_syslog.cfg`
but nothing has changed.

**Comment by v-zhuravlev** [comment]
rsyslog runs your scripts which normally runs under root. make sure that under root that you can test run script under root:
`/etc/zabbix/scripts/zabbix_syslog_lkp_host.pl '[xxx.xx.xx.xxx] kern.err /var/log/syslog'`

**Comment by msslava** [comment]
I run this command under the root and got
`[SYSLOG] Error received` in zabbix frontend

**Comment by v-zhuravlev** [comment]
thats trigger. Seems that it's working that way

**Comment by msslava** [comment]
All right. It's a triger. Only this trigger means NO DATA. Correctly? What else can I verify that the data began to arrive?

**Comment by v-zhuravlev** [comment]
check Latest data section, there should be syslog item there.

**Comment by msslava** [comment]
It's empty there. When I manually start the command
`/etc/zabbix/scripts/zabbix_syslog_lkp_host.pl '[xxx.xx.xx.xxx] kern.err /var/log/syslog'`
, then a value appears there.
Automatically nothing works.

**Comment by v-zhuravlev** [comment]
what Linux distribution do you use? Under which user does rsyslog run?

**Comment by msslava** [comment]
Ubuntu Server 16.04.
Under root

**Comment by v-zhuravlev** [comment]
Трудно сказать в чем дело. Покажите конфиг rsyslog

**Comment by msslava** [comment]
`
$ModLoad imuxsock # provides support for local system logging
$ModLoad imklog   # provides kernel logging support
#$ModLoad immark  # provides --MARK-- message capability

$ModLoad imudp
$UDPServerRun 514

$ModLoad imtcp
$InputTCPServerRun 514

$KLogPermitNonKernelFacility on

$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

$RepeatedMsgReduction on

$FileOwner syslog
$FileGroup adm
$FileCreateMode 0640
$DirCreateMode 0755
$Umask 0022
$PrivDropToUser syslog
$PrivDropToGroup syslog

$WorkDirectory /var/spool/rsyslog

$IncludeConfig /etc/rsyslog.d/*.conf
`

**Comment by v-zhuravlev** [comment]
подождите, а где запуск скрипта? в /etc/rsyslog.d/zabbix_rsyslog.conf?

**Comment by msslava** [comment]
Это был конфиг /etc/rsyslog.conf.
Вот это конфиг /etc/rsyslog.d/zabbix_rsyslog.conf

`$template RFC3164fmt,"<%PRI%>%TIMESTAMP% %HOSTNAME% %syslogtag%%msg%"
$template network-fmt,"%TIMESTAMP:::date-rfc3339% [%fromhost-ip%] %pri-text% %syslogtag%%msg%\n"


#exclude unwanted messages:
:msg, contains, "Child connection from" ~
:msg, contains, "exit after auth (ubnt): Disconnect received" ~
:msg, contains, "password auth succeeded for 'ubnt' from ::ffff:xxx.xx.xx.xx" ~
:msg, contains, "password auth succeeded for 'ubnt' from" ~
:msg, contains, "exit before auth: Exited normally" ~
if $fromhost-ip != '127.0.0.1' then ^/etc/zabbix/scripts/zabbix_syslog_lkp_host.pl;network-fmt
if $fromhost-ip != '127.0.0.1' then /var/log/network.log;network-fmt
& ~
`
Не понимаю, я что-то упустил?

**Comment by v-zhuravlev** [comment]
Попробуйте пожалуйста новый обновленный скрипт:
Many problems were related that CHI module actually could no be found for rsyslog in Centos 7 under root if installed with cpanm or CPAN. Please try new version of script without CHI: 
https://github.com/v-zhuravlev/zabbix-syslog/releases/tag/v3.1

**Comment by msslava** [comment]
Здравствуйте, подменил скрипты, запускаю команду:
`/etc/zabbix/scripts/zabbix_syslog_lkp_host.pl '[127.0.0.1] syslog.info Test syslog message'`
в ответ получаю:
`Can't open [127.0.0.1] syslog.info Test syslog message: No such file or directory at /etc/zabbix/scripts/zabbix_syslog_lkp_host.pl line 43.`
И так на любой ip.
Не подскажите, в чем ошибка?

**Comment by v-zhuravlev** [comment]
Скрипт поменялся, для работы с omprog(модуль rsyslog) и теперь требуется данные подавать через STDIN, а не параметром. Посмотрите обновленный README

**Comment by msslava** [comment]
Спасибо за помощь. 
Первый тест проходит нормально. В логах заббикса отображается информация подаваемая в инпут.
А вот второй тест не проходит:
1) запускаю rsyslog в интерактивном режиме
2) в параллельной сессии ввожу необходимые данные
3) в интерактивном режиме падает такое:
`Please check that config file is available as /usr/local/etc/zabbix_syslog.cfg or /etc/zabbix/zabbix_syslog.cfg`
По обеим путям файлы существуют и читабельны.
В чем тут дело?

**Comment by v-zhuravlev** [comment]
Может конфиг-файл не может прочитать пользователь , под которым запускаете rsyslog в интерактивном режиме ?

Отправлено с телефона

**Comment by msslava** [comment]
Запускаю под root. Под root эти файлы читабельны.

**Comment by msslava** [comment]
Извините за беспокойство. Все-таки дело оказалось в правах. Сам напутал с доступом.
Теперь все работает отлично! Спасибо за Вашу работу!
