### ISSUE TITLE
zabbix_syslog_lkp_host.pl

### ISSUE THREAD

**Issue by ivs27** [v-zhuravlev/zabbix-syslog#4]
приветствую, возможно ли его переделать на использование DNS имен. у меня cisco оборудование к примеру в syslog пишет все с DNS именем. получается что скрипт не работает из-за того чт отам нет ip адреса я так полагаю....

**Comment by v-zhuravlev** [comment]
этот ip адрес добавляет не cisco, а rsyslog. Поэтому проблем быть не должно.

**Comment by ivs27** [comment]
Может тогда подскажите куда копать? В ubuntu в syslog есть ивенты от циски что был выполнен вход выход, но в последних данных zabbix в item пусто. 

Отправлено с iPhone

**Comment by v-zhuravlev** [comment]
Попробуйте пожалуйста новый обновленный скрипт:
Many problems were related that CHI module actually could no be found for rsyslog in Centos 7 under root if installed with cpanm or CPAN. Please try new version of script without CHI: 
https://github.com/v-zhuravlev/zabbix-syslog/releases/tag/v3.1
