### ISSUE TITLE
Not working on all hosts.

### ISSUE THREAD

**Issue by markeczzz** [v-zhuravlev/zabbix-syslog#8]
I configured template as described in readme file.
I have two hosts, 192.168.1.10 and 192.168.1.20. On 192.168.1.10 host everything is working as it should, I am getting information in zabbix, but on the host 192.168.1.20 I am getting nothing. 
Both hosts are forwarding theirs logs to rsyslogd (192.168.1.5) which is running on same server as zabbix server. I can see messages from both hosts is syslog file on rsyslog server.
If I try to manually run 
`echo "2017-12-19T09:26:26.314936+03:00 [192.168.1.20] syslog.info SysLogTest[4616]Test syslog message" | /etc/zabbix/scripts/zabbix_syslog_lkp_host.pl` 
I get information in zabbix.
Both hosts are configured exactly the same in zabbix.

**Comment by v-zhuravlev** [comment]
Hi! try this:  https://github.com/v-zhuravlev/zabbix-syslog#suggested-test-2 to see what actually happens when second host sends message to rsyslog.

**Comment by markeczzz** [comment]
If I try with host which is working ok in zabbix, I get this: `host - srv1, item - syslog, data - 2018-04-19T14:20:32.867517+02:00 [192.168.1.10] user.notice roothello
answer from zabbix server localhost: OK`
but if I try with host other host i get only this: `Failed to retrieve any host interface with IP = 192.168.1.20. Unable to bind message to item, skipping`

**Comment by markeczzz** [comment]
Well, I fixed it. On host which wasn't working ok were two network interfaces, one bridge and one physical interface. Zabbix was listening on physical interface instead of bridge, and rsyslog was sending information via bridge interface, ie. different ip address to rsyslog server. 
I change IP address of host in zabbix config to bridge IP address and voila, everything is working
