### ISSUE TITLE
Getting error saying zabbix_syslog.cfg doesn't exist, but it does

### ISSUE THREAD

**Issue by Altranoetic** [v-zhuravlev/zabbix-syslog#9]
The title pretty much says it. I'm doing the second test suggested on the site. I turned off "rsyslog.service" and "syslog.socket", and ran rsyslogd -n. On another computer on the same network I ran "logger -n [ip]", and typed a few things in. I checked to see if they showed up in the log itself, and they do, but in the output of rsyslogd -n I'm only getting the following error:

`Please check that config file is available as /usr/local/etc/zabbix_syslog.cfg or /etc/zabbix/zabbix_syslog.cfg`

I made sure the zabbix_syslog.cfg file was in the right spot and had the right username and password. I'm not sure what else to check.

**Comment by v-zhuravlev** [comment]
file permissions?

**Comment by Altranoetic** [comment]
That's what it was, thanks!!
